#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AudioSamples.Resource", IsApplication=true)]

namespace AudioSamples
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000c
			public const int audioFocus = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int endPlaybackButton = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int endRecordingButton = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int llEndPlaybackButton = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int llEndRecordingButton = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int llStartPlaybackButton = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int llStartRecordingButton = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int lowLevelTitle = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int notificationsTitle = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int startPlaybackButton = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int startRecordingButton = 2131099649;
			
			// aapt resource value: 0x7f06000d
			public const int status = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int title = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int useNotificationsCheckBox = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AudioView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
