#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("StyleSamples.Resource", IsApplication=true)]

namespace StyleSamples
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060005
			public const int black = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int blue = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int custom_theme_color = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int green = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int red = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int white = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int yellow = 2131099651;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int editText1 = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int text_id = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int OneView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TwoView = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int CodeFont = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int CodeFont_Red = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int CodeFont_Red_Big = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int CustomFontStyle = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int CustomTheme = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int Mono_Android_Theme_Splash = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int Numbers = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int PinkTheme = 2131034120;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
