#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LinearAndRelativeLayoutSample.Resource", IsApplication=true)]

namespace LinearAndRelativeLayoutSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int thumb2 = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int DynamicTableLayout = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int GridViewRoot = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int TextLayout = 2131099660;
			
			// aapt resource value: 0x7f06001b
			public const int TextView01 = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int TextView02 = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int TextView03 = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int TextView04 = 2131099672;
			
			// aapt resource value: 0x7f060007
			public const int btnCancel = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int btnCreate = 2131099656;
			
			// aapt resource value: 0x7f060011
			public const int dates = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int firstLine = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int frameLayout1 = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int icon = 2131099659;
			
			// aapt resource value: 0x7f060013
			public const int imageView1 = 2131099667;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060010
			public const int name = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int scrollView1 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int secondLine = 2131099662;
			
			// aapt resource value: 0x7f060005
			public const int spinBestOf = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int spinBracketType = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int spinGameName = 2131099652;
			
			// aapt resource value: 0x7f060014
			public const int tableLayout1 = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int tableRow1 = 2131099671;
			
			// aapt resource value: 0x7f06001c
			public const int tableRow2 = 2131099676;
			
			// aapt resource value: 0x7f060023
			public const int tableRow3 = 2131099683;
			
			// aapt resource value: 0x7f060015
			public const int tableRow4 = 2131099669;
			
			// aapt resource value: 0x7f060002
			public const int textView1 = 2131099650;
			
			// aapt resource value: 0x7f06001d
			public const int textView2 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int textView3 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int textView4 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int textView5 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int textView6 = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int textView7 = 2131099682;
			
			// aapt resource value: 0x7f060024
			public const int textView8 = 2131099684;
			
			// aapt resource value: 0x7f060016
			public const int textView9 = 2131099670;
			
			// aapt resource value: 0x7f060012
			public const int times = 2131099666;
			
			// aapt resource value: 0x7f060003
			public const int tourName = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActionBarLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ComplexRelativeLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DynamicTable = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FrameLayoutView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int GridViewLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ItemView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int LinearLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int RelativeLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int RelativeLayoutOne = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int simple_fragment = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int TableLayout = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int sessions_tab_label = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int speakers_tab_label = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int whatson_tab_label = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
