#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ListViewSamles.Resource", IsApplication=true)]

namespace ListViewSamles
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04002c
			public const int AliceBlue = 2130968620;
			
			// aapt resource value: 0x7f040022
			public const int AntiqueWhite = 2130968610;
			
			// aapt resource value: 0x7f04007c
			public const int Aqua = 2130968700;
			
			// aapt resource value: 0x7f040061
			public const int Aquamarine = 2130968673;
			
			// aapt resource value: 0x7f040027
			public const int Beige = 2130968615;
			
			// aapt resource value: 0x7f04000d
			public const int Bisque = 2130968589;
			
			// aapt resource value: 0x7f04008b
			public const int Black = 2130968715;
			
			// aapt resource value: 0x7f04000b
			public const int BlanchedAlmond = 2130968587;
			
			// aapt resource value: 0x7f040087
			public const int Blue = 2130968711;
			
			// aapt resource value: 0x7f04005a
			public const int BlueViolet = 2130968666;
			
			// aapt resource value: 0x7f04004e
			public const int Brown = 2130968654;
			
			// aapt resource value: 0x7f040034
			public const int BurlyWood = 2130968628;
			
			// aapt resource value: 0x7f04006c
			public const int CadetBlue = 2130968684;
			
			// aapt resource value: 0x7f040062
			public const int Chartreuse = 2130968674;
			
			// aapt resource value: 0x7f04003e
			public const int Chocolate = 2130968638;
			
			// aapt resource value: 0x7f040017
			public const int Coral = 2130968599;
			
			// aapt resource value: 0x7f04006b
			public const int CornflowerBlue = 2130968683;
			
			// aapt resource value: 0x7f040007
			public const int Cornsilk = 2130968583;
			
			// aapt resource value: 0x7f040037
			public const int Crimson = 2130968631;
			
			// aapt resource value: 0x7f04007d
			public const int Cyan = 2130968701;
			
			// aapt resource value: 0x7f040089
			public const int DarkBlue = 2130968713;
			
			// aapt resource value: 0x7f040083
			public const int DarkCyan = 2130968707;
			
			// aapt resource value: 0x7f040046
			public const int DarkGoldenrod = 2130968646;
			
			// aapt resource value: 0x7f04004d
			public const int DarkGray = 2130968653;
			
			// aapt resource value: 0x7f040086
			public const int DarkGreen = 2130968710;
			
			// aapt resource value: 0x7f040043
			public const int DarkKhaki = 2130968643;
			
			// aapt resource value: 0x7f040058
			public const int DarkMagenta = 2130968664;
			
			// aapt resource value: 0x7f04006d
			public const int DarkOliveGreen = 2130968685;
			
			// aapt resource value: 0x7f040016
			public const int DarkOrange = 2130968598;
			
			// aapt resource value: 0x7f040051
			public const int DarkOrchid = 2130968657;
			
			// aapt resource value: 0x7f040059
			public const int DarkRed = 2130968665;
			
			// aapt resource value: 0x7f040031
			public const int DarkSalmon = 2130968625;
			
			// aapt resource value: 0x7f040056
			public const int DarkSeaGreen = 2130968662;
			
			// aapt resource value: 0x7f040070
			public const int DarkSlateBlue = 2130968688;
			
			// aapt resource value: 0x7f040076
			public const int DarkSlateGray = 2130968694;
			
			// aapt resource value: 0x7f040081
			public const int DarkTurquoise = 2130968705;
			
			// aapt resource value: 0x7f040053
			public const int DarkViolet = 2130968659;
			
			// aapt resource value: 0x7f04001b
			public const int DeepPink = 2130968603;
			
			// aapt resource value: 0x7f040082
			public const int DeepSkyBlue = 2130968706;
			
			// aapt resource value: 0x7f040069
			public const int DimGray = 2130968681;
			
			// aapt resource value: 0x7f04007a
			public const int DodgerBlue = 2130968698;
			
			// aapt resource value: 0x7f040047
			public const int FireBrick = 2130968647;
			
			// aapt resource value: 0x7f040005
			public const int FloralWhite = 2130968581;
			
			// aapt resource value: 0x7f040078
			public const int ForestGreen = 2130968696;
			
			// aapt resource value: 0x7f04001c
			public const int Fuchsia = 2130968604;
			
			// aapt resource value: 0x7f040036
			public const int Gainsboro = 2130968630;
			
			// aapt resource value: 0x7f040024
			public const int GhostWhite = 2130968612;
			
			// aapt resource value: 0x7f040039
			public const int Goldenrod = 2130968633;
			
			// aapt resource value: 0x7f04005d
			public const int Gray = 2130968669;
			
			// aapt resource value: 0x7f040085
			public const int Green = 2130968709;
			
			// aapt resource value: 0x7f04004b
			public const int GreenYellow = 2130968651;
			
			// aapt resource value: 0x7f04002b
			public const int Honeydew = 2130968619;
			
			// aapt resource value: 0x7f040018
			public const int HotPink = 2130968600;
			
			// aapt resource value: 0x7f040040
			public const int IndianRed = 2130968640;
			
			// aapt resource value: 0x7f04006e
			public const int Indigo = 2130968686;
			
			// aapt resource value: 0x7f040001
			public const int Ivory = 2130968577;
			
			// aapt resource value: 0x7f04002d
			public const int Khaki = 2130968621;
			
			// aapt resource value: 0x7f040032
			public const int Lavender = 2130968626;
			
			// aapt resource value: 0x7f040009
			public const int LavenderBlush = 2130968585;
			
			// aapt resource value: 0x7f040063
			public const int LawnGreen = 2130968675;
			
			// aapt resource value: 0x7f040006
			public const int LemonChiffon = 2130968582;
			
			// aapt resource value: 0x7f04004c
			public const int LightBlue = 2130968652;
			
			// aapt resource value: 0x7f04002e
			public const int LightCoral = 2130968622;
			
			// aapt resource value: 0x7f040033
			public const int LightCyan = 2130968627;
			
			// aapt resource value: 0x7f040020
			public const int LightGoldenrodYellow = 2130968608;
			
			// aapt resource value: 0x7f040055
			public const int LightGreen = 2130968661;
			
			// aapt resource value: 0x7f04003c
			public const int LightGrey = 2130968636;
			
			// aapt resource value: 0x7f040013
			public const int LightPink = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int LightSalmon = 2130968597;
			
			// aapt resource value: 0x7f040079
			public const int LightSeaGreen = 2130968697;
			
			// aapt resource value: 0x7f04005b
			public const int LightSkyBlue = 2130968667;
			
			// aapt resource value: 0x7f040065
			public const int LightSlateGray = 2130968677;
			
			// aapt resource value: 0x7f040049
			public const int LightSteelBlue = 2130968649;
			
			// aapt resource value: 0x7f040002
			public const int LightYellow = 2130968578;
			
			// aapt resource value: 0x7f04007f
			public const int Lime = 2130968703;
			
			// aapt resource value: 0x7f040075
			public const int LimeGreen = 2130968693;
			
			// aapt resource value: 0x7f040021
			public const int Linen = 2130968609;
			
			// aapt resource value: 0x7f04001d
			public const int Magenta = 2130968605;
			
			// aapt resource value: 0x7f040060
			public const int Maroon = 2130968672;
			
			// aapt resource value: 0x7f04006a
			public const int MediumAquamarine = 2130968682;
			
			// aapt resource value: 0x7f040088
			public const int MediumBlue = 2130968712;
			
			// aapt resource value: 0x7f040045
			public const int MediumOrchid = 2130968645;
			
			// aapt resource value: 0x7f040054
			public const int MediumPurple = 2130968660;
			
			// aapt resource value: 0x7f040074
			public const int MediumSeaGreen = 2130968692;
			
			// aapt resource value: 0x7f040064
			public const int MediumSlateBlue = 2130968676;
			
			// aapt resource value: 0x7f040080
			public const int MediumSpringGreen = 2130968704;
			
			// aapt resource value: 0x7f04006f
			public const int MediumTurquoise = 2130968687;
			
			// aapt resource value: 0x7f040041
			public const int MediumVioletRed = 2130968641;
			
			// aapt resource value: 0x7f04007b
			public const int MidnightBlue = 2130968699;
			
			// aapt resource value: 0x7f040025
			public const int MintCream = 2130968613;
			
			// aapt resource value: 0x7f04000c
			public const int MistyRose = 2130968588;
			
			// aapt resource value: 0x7f04000e
			public const int Moccasin = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int NavajoWhite = 2130968591;
			
			// aapt resource value: 0x7f04008a
			public const int Navy = 2130968714;
			
			// aapt resource value: 0x7f04001f
			public const int OldLace = 2130968607;
			
			// aapt resource value: 0x7f04005e
			public const int Olive = 2130968670;
			
			// aapt resource value: 0x7f040067
			public const int OliveDrab = 2130968679;
			
			// aapt resource value: 0x7f040014
			public const int Orange = 2130968596;
			
			// aapt resource value: 0x7f04001a
			public const int OrangeRed = 2130968602;
			
			// aapt resource value: 0x7f04003a
			public const int Orchid = 2130968634;
			
			// aapt resource value: 0x7f04002f
			public const int PaleGoldenrod = 2130968623;
			
			// aapt resource value: 0x7f040052
			public const int PaleGreen = 2130968658;
			
			// aapt resource value: 0x7f04004a
			public const int PaleTurquoise = 2130968650;
			
			// aapt resource value: 0x7f040038
			public const int PaleVioletRed = 2130968632;
			
			// aapt resource value: 0x7f04000a
			public const int PapayaWhip = 2130968586;
			
			// aapt resource value: 0x7f040010
			public const int PeachPuff = 2130968592;
			
			// aapt resource value: 0x7f04003f
			public const int Peru = 2130968639;
			
			// aapt resource value: 0x7f040012
			public const int Pink = 2130968594;
			
			// aapt resource value: 0x7f040035
			public const int Plum = 2130968629;
			
			// aapt resource value: 0x7f040048
			public const int PowderBlue = 2130968648;
			
			// aapt resource value: 0x7f04005f
			public const int Purple = 2130968671;
			
			// aapt resource value: 0x7f04001e
			public const int Red = 2130968606;
			
			// aapt resource value: 0x7f040044
			public const int RosyBrown = 2130968644;
			
			// aapt resource value: 0x7f040072
			public const int RoyalBlue = 2130968690;
			
			// aapt resource value: 0x7f040057
			public const int SaddleBrown = 2130968663;
			
			// aapt resource value: 0x7f040029
			public const int SandyBrown = 2130968617;
			
			// aapt resource value: 0x7f040077
			public const int SeaGreen = 2130968695;
			
			// aapt resource value: 0x7f040008
			public const int Seashell = 2130968584;
			
			// aapt resource value: 0x7f04004f
			public const int Sienna = 2130968655;
			
			// aapt resource value: 0x7f040042
			public const int Silver = 2130968642;
			
			// aapt resource value: 0x7f04005c
			public const int SkyBlue = 2130968668;
			
			// aapt resource value: 0x7f040068
			public const int SlateBlue = 2130968680;
			
			// aapt resource value: 0x7f040066
			public const int SlateGray = 2130968678;
			
			// aapt resource value: 0x7f040004
			public const int Snow = 2130968580;
			
			// aapt resource value: 0x7f04007e
			public const int SpringGreen = 2130968702;
			
			// aapt resource value: 0x7f040071
			public const int SteelBlue = 2130968689;
			
			// aapt resource value: 0x7f04003d
			public const int Tan = 2130968637;
			
			// aapt resource value: 0x7f040084
			public const int Teal = 2130968708;
			
			// aapt resource value: 0x7f04003b
			public const int Thistle = 2130968635;
			
			// aapt resource value: 0x7f040019
			public const int Tomato = 2130968601;
			
			// aapt resource value: 0x7f040073
			public const int Turquoise = 2130968691;
			
			// aapt resource value: 0x7f040030
			public const int Violet = 2130968624;
			
			// aapt resource value: 0x7f040028
			public const int Wheat = 2130968616;
			
			// aapt resource value: 0x7f040000
			public const int White = 2130968576;
			
			// aapt resource value: 0x7f040026
			public const int WhiteSmoke = 2130968614;
			
			// aapt resource value: 0x7f040003
			public const int Yellow = 2130968579;
			
			// aapt resource value: 0x7f040050
			public const int YellowGreen = 2130968656;
			
			// aapt resource value: 0x7f04002a
			public const int azure = 2130968618;
			
			// aapt resource value: 0x7f040011
			public const int gold = 2130968593;
			
			// aapt resource value: 0x7f040023
			public const int salmon = 2130968611;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int one_custom_selector = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int Image = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int ListViewRoot = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int Text = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Text1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int Text2 = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int OneListViewItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int OneView = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
