#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AnimationSample.Resource", IsApplication=true)]

namespace AnimationSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f040000
			public const int hyperspace = 2130968576;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int android_blue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int android_green = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int android_red = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int asteroid01 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int asteroid02 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int asteroid03 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int asteroid04 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int asteroid05 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int asteroid06 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int button = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int button_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int button_hovered = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int button_normal = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int button_pressed = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Clip = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int gradient_box = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_launcher = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Icon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int image1 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int image2 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int inset = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int layers = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int LevelList = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int monoandroidsplash = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int off = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int on = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Scale = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Ship = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Signal1 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Signal2 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Signal3 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Signal4 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int spinning_asteroid = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int thumb1 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int thumb2 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int transition = 2130837540;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000a
			public const int ButtonDown = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int ButtonSpin = 2131165184;
			
			// aapt resource value: 0x7f070010
			public const int ButtonStart = 2131165200;
			
			// aapt resource value: 0x7f07000b
			public const int ButtonUp = 2131165195;
			
			// aapt resource value: 0x7f070007
			public const int ClipImageView = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int ImageLevelListDrawable = 2131165189;
			
			// aapt resource value: 0x7f070011
			public const int ImageShow = 2131165201;
			
			// aapt resource value: 0x7f070004
			public const int ImageTransitionDrawable = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int ImageViewAsteroid = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int InsertButton = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int KarmaMeter = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int KarmaSeeker = 2131165197;
			
			// aapt resource value: 0x7f070002
			public const int SCROLLER_ID = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int ScaleImageView = 2131165190;
			
			// aapt resource value: 0x7f07000f
			public const int SeekBarValueAnimator = 2131165199;
			
			// aapt resource value: 0x7f070003
			public const int TextViewShapeDrawableProgramatically = 2131165187;
			
			// aapt resource value: 0x7f070012
			public const int container = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int expanded_image = 2131165205;
			
			// aapt resource value: 0x7f07000c
			public const int frameLayout1 = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int textView1 = 2131165198;
			
			// aapt resource value: 0x7f070013
			public const int thumb_button_1 = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int thumb_button_2 = 2131165204;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AnimationDrawable = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Drawable = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Drawing = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PropertyAnimation = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ValueAnimator = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ViewAnimation = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Zoom = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int AnimationDrawable = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int DrawingActivity = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int PropertyAnimation = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int ShapeDrawable = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int ValueAnimation = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int ViewAnimation = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int ZoomActivity = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int description_image_1 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int description_image_2 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int description_zoom_touch_close = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int message_zoom_touch_expand = 2131034119;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
